version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "6000:6000"
    volumes:
      - ./data:/data
    networks:
      - mynetwork

  mongodb:
    image: mongo:3
    volumes:
      - ./data/db:/data/db
    networks:
      - mynetwork
    depends_on:
      - app

networks:
  mynetwork:
    driver: bridge
